spring.application.name=purchase-service
server.port=8082
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.level.root=INFO
logging.pattern.console={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","service":"catalog-service","message":"%m","thread":"%t"}%n